/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Login: typeof import('./src/components/Login.vue')['default']
    Read: typeof import('./src/components/Read.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Show: typeof import('./src/components/Show.vue')['default']
    Write: typeof import('./src/components/Write.vue')['default']
  }
}
